# Generated by Django 4.1.2 on 2023-01-14 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic_url',
        ),
    ]
